### ISSUE TITLE
How to get more details on storage consumption ?

### ISSUE THREAD

**Issue by tdupoiron** [KI-SSC-GitHub-Admin-and-Promotion/Atos_GitHub_Zero_Email_Channel#3]
This question was raised by Patrice during our last call.

Atos wants a fine-grained visibility on how is used Artifacts storage including GH Packages and Actions.
They want to know which workflow execution is consuming space and how long is the remaining retention period.

As a side question, what would be the best practices for Artifacts retention : business use case and costs optimisation.

**Comment by tdupoiron** [comment]
Hi @A163356, 
I've been working on Actions and Packages storage consumption last week.
Here are my findings and suggestions:

# Challenge:
It is currently not easy to observe Storage consumption for Actions and Packages.

At the Enterprise level, we can only see a consolidated consumption per organization.
<img width="873" alt="image" src="https://user-images.githubusercontent.com/7711190/204296944-3fe6cbf6-6f1b-49cb-bd07-95a2a320d669.png">

At the organization level, the experience is similar in the Billing settings.
<img width="530" alt="image" src="https://user-images.githubusercontent.com/7711190/204297055-71c272c8-3f0e-47b1-9cbf-d670bc69ed4c.png">

Atos would like more details on these numbers to understand for each artifact if it is permanently saved in Packages or temporary cached by a workflow run, in order to optimize costs.

# Feature Request:
This [release](https://github.com/github/roadmap/issues/615) of the fall 22’ roadmap is linked with a beta feature offering detailed charts in the organization insights.

Examples: 
- Various charts
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/7711190/204297490-8a39c904-f25a-482a-b68d-980283b1b9c8.png">

- Top 10 repos and workflows by billable minutes
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/7711190/204297546-d4484603-70ce-42a7-9d4a-efcdb1910d25.png">

This dashboard will be a great improvement but will still not cover Atos expectations for now.

# Solution:
To retrieve all artifacts and its metadata, it is currently required to invoke GitHub API and build a solution to visualize the data.

1 – [List repositories](https://docs.github.com/en/rest/repos/repos#list-organization-repositories) for an organization
2 – For each repository, [list artifacts](https://docs.github.com/en/rest/actions/artifacts#list-artifacts-for-a-repository)

I have started a small JavaScript development to demonstrate this in this [public repository](https://github.com/tdupoiron/github-artifacts).
A first app can be scheduled or trigger via actions to generate a Json file on a daily basis : 
```
  {
    "repoId": 564242926,
    "repoName": "sandbox",
    "repoVisibility": "private",
    "repoUrl": "https://github.com/tdupoiron-org/sandbox",
    "repoOwnerType": "Organization",
    "repoOwnerLogin": "tdupoiron-org",
    "repoOwnerUrl": "https://github.com/tdupoiron-org",
    "artifactId": 451221025,
    "artifactName": "openjdk-zulu.zip",
    "artifactDownloadUrl": "https://api.github.com/repos/tdupoiron-org/sandbox/actions/artifacts/451221025/zip",
    "workflowRunId": 3549368245,
    "workflowRunUrl": "https://github.com/tdupoiron-org/sandbox/actions/runs/3549368245",
    "size": 209756375,
    "created_at": "2022-11-25T16:13:39Z",
    "expires_at": "2023-02-23T16:12:33Z"
  }
```

Note that we can easily find [GitHub Actions](https://github.com/marketplace/actions/list-repository-artifacts) to do this.

A second app only displays the result in a [static GitHub page](https://tdupoiron.github.io/github-artifacts/).

 

I will improve this project in the following days, depending on your feedbacks.

**Comment by A163356** [comment]
Hi Thomas,

Thanks for the updates, we will send you feedback before end of this week.

Thanks & Regards.

[Atos logo]

Patrice Giraud
Head of Global COA/CO1/TOO/Engineering Tools
ATOS GitHub Enterprise Account Owner
Fixed Line: +33 488810250
M: +33 684626827
150 Allée Pierre Ziller, Le Millenium – 06905 SOPHIA ANTIPOLIS – France
atos.net<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fatos.net%2F&data=02%7C01%7Cpatrice.giraud%40atos.net%7C7457859a380d40835eb808d72d595a77%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637027735049472109&sdata=F%2Bz34GivIsOhaGaEE7lbci3%2BMy2Dvqe85LlmDru3yno%3D&reserved=0>






De : Thomas Dupoiron ***@***.***>
Envoyé : lundi 28 novembre 2022 15:10
À : KI-SSC-GitHub-Admin-and-Promotion/Atos_GitHub_Zero_Email_Channel ***@***.***>
Cc : PATRICE GIRAUD ***@***.***>; Mention ***@***.***>
Objet : Re: [KI-SSC-GitHub-Admin-and-Promotion/Atos_GitHub_Zero_Email_Channel] How to get more details on storage consumption ? (Issue #3)


Caution: External email. Do not open attachments or click links, unless this email comes from a known sender and you know the content is safe.



Hi @A163356<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FA163356&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xmaOr06K3eWyLBdWXiNQZMiEvkcwxtnB8Iw1yan8lUk%3D&reserved=0>,
I've been working on Actions and Packages storage consumption last week.
Here are my findings and suggestions:

Challenge:

It is currently not easy to observe Storage consumption for Actions and Packages.

At the Enterprise level, we can only see a consolidated consumption per organization.
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7711190%2F204296944-3fe6cbf6-6f1b-49cb-bd07-95a2a320d669.png&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BmghSje5XspBbE9BIf7gud9zh5B9gUXjYnoaTEUs1kk%3D&reserved=0>

At the organization level, the experience is similar in the Billing settings.
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7711190%2F204297055-71c272c8-3f0e-47b1-9cbf-d670bc69ed4c.png&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4sU44JWRb6qqX8yNo4aF1idZuVUEvP%2Bh7NQ%2FRLuQHUw%3D&reserved=0>

Atos would like more details on these numbers to understand for each artifact if it is permanently saved in Packages or temporary cached by a workflow run, in order to optimize costs.

Feature Request:

This release<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgithub%2Froadmap%2Fissues%2F615&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t3uP2f4kXSt9oRna0rgM2NDjV5iFoyaZSbNJ9nbD%2FKM%3D&reserved=0> of the fall 22’ roadmap is linked with a beta feature offering detailed charts in the organization insights.

Examples:

  *   Various charts

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7711190%2F204297490-8a39c904-f25a-482a-b68d-980283b1b9c8.png&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FPiCVX7L9CgBf3JqRvKZKdSAzLQi44OmaXEDfOppFLk%3D&reserved=0>

  *   Top 10 repos and workflows by billable minutes

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7711190%2F204297546-d4484603-70ce-42a7-9d4a-efcdb1910d25.png&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WAqwUJ5NuGXJ5%2BzaJxWcO961n%2BPxvXigGxvsRGOUQyQ%3D&reserved=0>

This dashboard will be a great improvement but will still not cover Atos expectations for now.

Solution:

To retrieve all artifacts and its metadata, it is currently required to invoke GitHub API and build a solution to visualize the data.

1 – List repositories<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.github.com%2Fen%2Frest%2Frepos%2Frepos%23list-organization-repositories&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A3Lg%2FeapOde84qS7RnO%2F9Bd1NoBK3ctE379qxcp3OHQ%3D&reserved=0> for an organization
2 – For each repository, list artifacts<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.github.com%2Fen%2Frest%2Factions%2Fartifacts%23list-artifacts-for-a-repository&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LHingXLvhtRwecJt3u2p5E4x6D7gfoYahyU7mOH7zrw%3D&reserved=0>

I have started a small JavaScript development to demonstrate this in this public repository<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftdupoiron%2Fgithub-artifacts&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DwThNRXNaTB4YB%2FjWpZ1mKPftsyW00cNgCY0%2Bxtb29I%3D&reserved=0>.
A first app can be scheduled or trigger via actions to generate a Json file on a daily basis :

  {



    "repoId": 564242926,



    "repoName": "sandbox",



    "repoVisibility": "private",



    "repoUrl": "https://github.com/tdupoiron-org/sandbox",



    "repoOwnerType": "Organization",



    "repoOwnerLogin": "tdupoiron-org",



    "repoOwnerUrl": "https://github.com/tdupoiron-org",



    "artifactId": 451221025,



    "artifactName": "openjdk-zulu.zip",



    "artifactDownloadUrl": "https://api.github.com/repos/tdupoiron-org/sandbox/actions/artifacts/451221025/zip",



    "workflowRunId": 3549368245,



    "workflowRunUrl": "https://github.com/tdupoiron-org/sandbox/actions/runs/3549368245",



    "size": 209756375,



    "created_at": "2022-11-25T16:13:39Z",



    "expires_at": "2023-02-23T16:12:33Z"



  }



Note that we can easily find GitHub Actions<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarketplace%2Factions%2Flist-repository-artifacts&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DTBiWem9XRNgztHZqKry%2F6ZGGVbuegPgiG%2BpLbWCww4%3D&reserved=0> to do this.

A second app only displays the result in a static GitHub page<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftdupoiron.github.io%2Fgithub-artifacts%2F&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6EXZ9IKQrz5qX%2BNONEYXv9yvaM3yTY8%2BIDQ7o8hAyzY%3D&reserved=0>.

I will improve this project in the following days, depending on your feedbacks.

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKI-SSC-GitHub-Admin-and-Promotion%2FAtos_GitHub_Zero_Email_Channel%2Fissues%2F3%23issuecomment-1329174496&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929487697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yGvRqvkHZbd3KY9Aajnfus3tEP2gKv51NFRmZ4U%2Fi%2FU%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB5MHF76MLQBWJMWMTUFVTLWKS4KZANCNFSM6AAAAAASIVKJRA&data=05%7C01%7Cpatrice.giraud%40atos.net%7C7d1a95f004ca4ce0be3408dad14a367d%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C638052413929643928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BI%2BybmnKsPcR9de79LnHmU4bETzA95nlfaPUajdMABE%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l’intention exclusive des destinataires désignés. Il contient des informations confidentielles et pouvant être protégé par le secret professionnel. Si vous recevez ce message par erreur, merci d'en avertir immédiatement l'expéditeur et de détruire le message. Toute utilisation de ce message non conforme à sa destination, toute diffusion ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse de l’émetteur. L'internet ne garantissant pas l'intégrité de ce message lors de son acheminement, Atos (et ses filiales) décline(nt) toute responsabilité au titre de son contenu. Bien que ce message ait fait l’objet d’un traitement anti-virus lors de son envoi, l’émetteur ne peut garantir l’absence totale de logiciels malveillants dans son contenu et ne pourrait être tenu pour responsable des dommages engendrés par la transmission de l’un d’eux.

This message and any attachments (the "message") are intended solely for the addressee(s). It contains confidential information, that may be privileged. If you receive this message in error, please notify the sender immediately and delete the message. Any use of the message in violation of its purpose, any dissemination or disclosure, either wholly or partially is strictly prohibited, unless it has been explicitly authorized by the sender. As its integrity cannot be secured on the internet, Atos and its subsidiaries decline any liability for the content of this message. Although the sender endeavors to maintain a computer virus-free network, the sender does not warrant that this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted.

**Comment by tdupoiron** [comment]
Patrice, I forgot to mention the CSV export, available from your organization billing settings.
![Image](https://user-images.githubusercontent.com/7711190/204827971-4488de7e-f790-47bf-84e7-16f7bd0dd420.png)
It explains the costs, day x repo. However, it still does not drill down into the artifacts.


![Image](https://user-images.githubusercontent.com/7711190/204829529-e3eadd15-b8f1-4108-a756-80d934638e98.png)

**Comment by tdupoiron** [comment]
- [ ] Thomas to plan a workshop with Mughda and Mayur to present the app, learn about alerts challenges and set the dev environment to use GitHub Apps.
